services:
    nginx:
        image: nginx:latest
        hostname: web-apache
        ports:
            - '80:80'
            - '443:443'
        volumes:
            - ./prestashop_8.2.1:/app
            - ./certificados:/certs
            - ./nginx-lemp/vhost.lemp.conf:/etc/nginx/conf.d/vhost.lemp.conf

        networks:
            redelamplemp:
                aliases:
                    - braisgp.tech
                    - www.braisgp.tech
        env_file:
            - .env_dev
    phpserver:
        build: php-lemp
        volumes:
            - ./prestashop_8.2.1:/app
              - ./apache-php-lamp/php.ini:/etc/php/8.1/apache2/php.ini
            - ./nginx-lemp/www.conf:/etc/php/{version}/fpm/pool.d/www.conf
        networks:
            redelamplemp:
    basededatos:
        image: mysql:latest
        ports:
            - 3306:3306
        env_file:
            - .env_dev
        environment:
            MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
            MYSQL_PASSWORD_FILE: /run/secrets/db_braisgp_password
        secrets:
            - db_root_password
            - db_braisgp_password
        volumes:
            - ./bd/backup:/docker-entrypoint-initdb.d
            - ./bd/backup:/backup
            - datos:/var/lib/mysql
        networks:
            redelamplemp:
    cliente:
        image: brunosct/debian12-cliente-firefox
        networks:
            - redelamplemp
        environment:
            - DISPLAY=${DISPLAY}
        volumes:
            - /tmp/.X11-unix:/tmp/.X11-unix:ro
            - ${XAUTHORITY}:${XAUTHORITY}
        privileged: true

volumes:
    datos:
networks:
    redelamplemp:
secrets:
    db_root_password:
        file: ./db_root_password.txt
    db_braisgp_password:
        file: ./db_braisgp_password.txt
