services:
    nginx:
        image: nginx:latest
        hostname: web-apache
        ports:
            - '80:80'
            - '443:443'
        volumes:
            - ./prestashop_8.2.1:/app
            - ./certificados:/certs
            - ./nginx-lemp/vhost.lemp.conf:/etc/nginx/conf.d/vhost.lemp.conf
            - ./apache-php-lamp/php.ini:/etc/php/8.1/apache2/php.ini
            - ./nginx-lemp/www.conf:/etc/php/{version}/fpm/pool.d/www.conf
        networks:
            redelamplemp:
                aliases:
                    - braisgp.tech
                    - www.braisgp.tech
        env_file:
            - .evn_prod
    phpserver:
        build: php-lemp
        volumes:
            - ./prestashop_8.2.1:/app
            - ./apache-php-lamp/php.ini:/etc/php/8.1/fpm/php.ini
            - ./nginx-lemp/www.conf:/etc/php/8.1/fpm/pool.d/www.conf
        env_file:
            - .env_prod
        networks:
            redelamplemp:

volumes:
    datos:
networks:
    redelamplemp:
