services:
    apache:
        build: apache-php-lamp
        ports:
            - '8000:80'
            - '8443:443'
        volumes:
            - ./prestashop_8.2.1:/app
            - ./certificados:/certs
            - ./apache-php-lamp/vhost:/etc/apache2/sites-enabled
        networks:
            redelamplemp:
                aliases:
                    - braisgp.tech
                    - www.braisgp.tech
    basededatos:
        image: mysql:latest
        env_file:
            - .env_bd
        secrets:
            - db_root_password
            - db_braisgp_password
        volumes:
            - datos:/var/lib/mysql
        networks:
            redelamplemp:
    #phpmyadmin se se necesita
    cliente:
        hostname: cliente
        image: brunosct/debian12-cliente-firefox
        networks:
            - redelamplemp
        environment:
            - DISPLAY=${DISPLAY}
        volumes:
            - /tmp/.X11-unix:/tmp/.X11-unix
volumes:
    datos:
networks:
    redelamplemp:
