<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerEueTfUf\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerEueTfUf/appAppKernelProdContainer.php') {
    touch(__DIR__.'/ContainerEueTfUf.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\ContainerEueTfUf\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \ContainerEueTfUf\appAppKernelProdContainer([
    'container.build_hash' => 'EueTfUf',
    'container.build_id' => 'b8ea5663',
    'container.build_time' => 1741780262,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerEueTfUf');
